version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
    - method: pip
      pip_install: true
      requirements: false
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py

# Use poetry to install dependencies
build:
  jobs:
    pre_build:
      - pip install poetry
      - poetry install --with docs
