version: 2

# Use poetry to install dependencies
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install poetry
      - poetry install --with docs
    build:
      html:
        - poetry run sphinx-build -T -b html -d _build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
