codecov:
  require_ci_to_pass: no

comment:
  layout: "none"

coverage:
  status:
    project:
      default:
        enabled: no
    patch:
      default:
        enabled: no
  exclude:
    - "andebox/__main__.py"
