#!/bin/sh
# code: language=shell tabSize=2
#
# (C) 2025 Alexei Znamensky
# Licensed under the MIT License. See LICENSES/MIT.txt for details.
# SPDX-FileCopyrightText: 2025 Alexei Znamensky
# SPDX-License-Identifier: MIT
#

DIR=$(pwd)
WORKDIR=/workdir

COLS=124
ROWS=32

export SCENE_FILE=$DIR/$1
export CAST_FILE=$DIR/$2

sudo mkdir -p $WORKDIR
sudo chown -R $(id -u):$(id -g) $WORKDIR
(
    cd $WORKDIR;
    asciinema rec --quiet \
        --cols $COLS --rows $ROWS \
        --command asciinwriter \
        --overwrite $CAST_FILE
)
sudo rm -rf $WORKDIR
