#!/bin/sh
# code: language=shell tabSize=2
# Copyright (c) 2025, Alexei Znamensky
# All rights reserved.
#
# This file is part of the Andebox project and is distributed under the terms
# of the BSD 3-Clause License. See LICENSE file for details.

DIR=$(pwd)
WORKDIR=/workdir

COLS=124
ROWS=32

export PEXP_FILE=$DIR/$1
export CAST_FILE=$DIR/$2

sudo mkdir -p $WORKDIR
sudo chown -R $(id -u):$(id -g) $WORKDIR
(
    cd $WORKDIR;
    asciinema rec --quiet \
        --cols $COLS --rows $ROWS \
        --command ${DIR}/pexp \
        --overwrite $CAST_FILE
)
sudo rm -rf $WORKDIR
