#!/bin/sh
# code: language=shell tabSize=2
#
# (C) 2025 Alexei Znamensky
# Licensed under the MIT License. See LICENSES/MIT.txt for details.
# SPDX-FileCopyrightText: 2025 Alexei Znamensky
# SPDX-License-Identifier: MIT
#

sudo apt update
sudo apt install -y \
    asciinema \
    gifsicle

pip install --user pexpect andebox
