#!/bin/sh
# code: language=shell tabSize=2
# Copyright (c) 2025, Alexei Znamensky
# All rights reserved.
#
# This file is part of the Andebox project and is distributed under the terms
# of the BSD 3-Clause License. See LICENSE file for details.

sudo apt update
sudo apt install -y \
    asciinema \
    gifsicle

pip install --user pexpect andebox
